### ISSUE TITLE
Dockerhub links broken

### ISSUE THREAD

**Issue by adamculp** [phpqa/phpqa.github.io#22]
The DockerHub links are all broken. What is the intent for them?

Currently all pointing to https://hub.docker.com/r/, but I think you meant for them to point to the various images at https://hub.docker.com/u/phpqa/.

**Comment by MetalArend** [comment]
I'm currently trying to figure out how to automatically build them every night, to keep up with the correct version numbers. But right now, this makes no sense like this :/

**Comment by adamculp** [comment]
I think this project is a good one. Very good resource.

**Comment by MetalArend** [comment]
Fixed the links in the latest push. Thanks for reporting this.
