### ISSUE TITLE
Phpactor and phpa (php assumptions) have the same docker hub link : phpqa/phpa

### ISSUE THREAD

**Issue by iceberg53** [phpqa/phpqa.github.io#24]
I just discovered your website at https://phpqa.io/ and while browsing the available tools,  I noticed that phpactor and phpa(php assumptions) are listed with the same docker link : https://hub.docker.com/r/phpqa/phpa .

I checked your docker hub profile to see if the docker images for both actually exist but found that there's only an image for phpa which link is the one provided above.

Thus, I wanted to let you know that.

BTW, thank you for the initiative.

**Comment by MetalArend** [comment]
You are completely right. I fixed the phpactor info, thanks for pointing this out. I hope you enjoy phpqa.io.
