### ISSUE TITLE
Update twitter bootstrap to beta 1 to resolve the "Tooltip is transitioning" error

### ISSUE THREAD

**Issue by MetalArend** [phpqa/phpqa.github.io#4]
The bootstrap 4 version throws the error "Tooltip is transitioning", [a fix](https://github.com/twbs/bootstrap/issues/21607) is being released in the next beta version.

**Comment by Syden10** [comment]
Great that it's being addressed! As a temporary fix until beta 1 is released, add `data-animation="false"` to the `data-toggle="tooltip"` html element.

**Comment by MetalArend** [comment]
Thanks, @Syden10, for the tip (no pun intended).

**Comment by MetalArend** [comment]
Fixed in the latest Bootstrap update.
